//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     请不要对该文件内容进行修改。如果重新生成代码，文件内容将被覆盖。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Core
{
    public partial class Tfmonitorabnormal : IEntity<int>
    {
        public Tfmonitorabnormal()
        {
        }
        
        public bool IsTransient()
        {
            return EqualityComparer<int>.Default.Equals(this.Id, default(int));
        }

        /// <summary>
        /// 
        /// </summary>    
        public int Id { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Exception { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string AbnormalContext { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string AddressName { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime? StartTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime? EndTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string MaxAlarmValue { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime? MaxAlarmTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Reason { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Remarks { get; set; }

    }
}