//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Abp.Application.Services.Dto;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Application
{
    public partial class ZtconstructionsiteDto : IEntityDto<int>, IInputDto, IOutputDto
    {
        /// <summary>
        /// 
        /// </summary>    
        public int Id { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string ConstructionSiteName { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string LastDrillingRig { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? LastMonthlyPlan { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string LastTeam { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? PoreSize { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int State { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public bool IsDeleted { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int StartMonthlyPlan { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CreationTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Remarks { get; set; }

    }
}

