//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     请不要对该文件内容进行修改。如果重新生成代码，文件内容将被覆盖。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Core
{
    public partial class Tfmonitoranalog : IEntity<int>,IHasCreationTime
    {
        public Tfmonitoranalog()
        {
        }
        
        public bool IsTransient()
        {
            return EqualityComparer<int>.Default.Equals(this.Id, default(int));
        }

        /// <summary>
        /// 
        /// </summary>    
        public int Id { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int AddressId { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int SysType { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int MonitorType { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? MaxValue { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string MaxMomentValue { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? MinValue { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string MinMomentValue { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? DailyAverageValue { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? OutCount { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CreationTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CollectionTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Remarks { get; set; }

        public virtual Cmaddress AddressCmaddress { get; set; }
    }
}