//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Abp.Application.Services.Dto;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Application
{
    public partial class GetBsmenubuttonPageInput : DefaultPagedResultRequest
    {
        
        /// <summary>
        /// 
        /// </summary>    
        public int? Id { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? ButtonId { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? MenuId { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string ButtonText { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string RunEvent { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string IconClass { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public bool? IsActive { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? Sort { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime? LastModificationTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public long? LastModifierUserId { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public long? CreatorUserId { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime? CreationTime { get; set; }
    }
}

