//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using Abp.EntityFramework;
using CodeSmith.Abp.Template.Test.Core;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.EntityFramework
{
    public partial class BsbuttonMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Bsbutton>
    {
        public BsbuttonMap()
        {
            // table
            ToTable("bsbutton");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.Text)
                .HasColumnName("Text")
                .HasMaxLength(150)
                .IsRequired();
            Property(t => t.RunEvent)
                .HasColumnName("RunEvent")
                .HasMaxLength(150)
                .IsRequired();
            Property(t => t.IconClass)
                .HasColumnName("IconClass")
                .HasMaxLength(150)
                .IsOptional();
            Property(t => t.CreationTime)
                .HasColumnName("CreationTime")
                .IsRequired();
            Property(t => t.CreatorUserId)
                .HasColumnName("CreatorUserId")
                .IsOptional();
            Property(t => t.LastModificationTime)
                .HasColumnName("LastModificationTime")
                .IsOptional();
            Property(t => t.LastModifierUserId)
                .HasColumnName("LastModifierUserId")
                .IsOptional();

            // Relationships

            InitializeMapping();
        }
    }
}
