//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using Abp.EntityFramework;
using CodeSmith.Abp.Template.Test.Core;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.EntityFramework
{
    public partial class BsdictionaryMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Bsdictionary>
    {
        public BsdictionaryMap()
        {
            // table
            ToTable("bsdictionary");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.ParentId)
                .HasColumnName("ParentId")
                .IsOptional();
            Property(t => t.ParentIds)
                .HasColumnName("ParentIds")
                .HasMaxLength(150)
                .IsRequired();
            Property(t => t.DictionaryKey)
                .HasColumnName("DictionaryKey")
                .HasMaxLength(150)
                .IsOptional();
            Property(t => t.DictionaryName)
                .HasColumnName("DictionaryName")
                .HasMaxLength(150)
                .IsRequired();
            Property(t => t.DictionaryValue)
                .HasColumnName("DictionaryValue")
                .HasMaxLength(150)
                .IsOptional();
            Property(t => t.IsActive)
                .HasColumnName("IsActive")
                .IsRequired();
            Property(t => t.IsDeleted)
                .HasColumnName("IsDeleted")
                .IsRequired();
            Property(t => t.IsGroup)
                .HasColumnName("IsGroup")
                .IsRequired();
            Property(t => t.CreatorUserId)
                .HasColumnName("CreatorUserId")
                .IsOptional();
            Property(t => t.CreationTime)
                .HasColumnName("CreationTime")
                .IsRequired();
            Property(t => t.LastModifierUserId)
                .HasColumnName("LastModifierUserId")
                .IsOptional();
            Property(t => t.LastModificationTime)
                .HasColumnName("LastModificationTime")
                .IsOptional();
            Property(t => t.Sort)
                .HasColumnName("Sort")
                .IsRequired();
            Property(t => t.Remarks)
                .HasColumnName("Remarks")
                .HasMaxLength(30)
                .IsOptional();

            // Relationships
            HasOptional(t => t.ParentBsdictionary)
                .WithMany(t => t.ParentBsdictionaries)
                .HasForeignKey(d => d.ParentId)
                .WillCascadeOnDelete(false);
            HasOptional(t => t.CreatorUserBsuser)
                .WithMany(t => t.CreatorUserBsdictionaries)
                .HasForeignKey(d => d.CreatorUserId)
                .WillCascadeOnDelete(false);
            HasOptional(t => t.LastModifierUserBsuser)
                .WithMany(t => t.LastModifierUserBsdictionaries)
                .HasForeignKey(d => d.LastModifierUserId)
                .WillCascadeOnDelete(false);
            HasOptional(t => t.ParentBsdictionary1)
                .WithMany(t => t.ParentBsdictionaries1)
                .HasForeignKey(d => d.ParentId)
                .WillCascadeOnDelete(false);

            InitializeMapping();
        }
    }
}
