//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using Abp.EntityFramework;
using CodeSmith.Abp.Template.Test.Core;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.EntityFramework
{
    public partial class BspermissionMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Bspermission>
    {
        public BspermissionMap()
        {
            // table
            ToTable("bspermission");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.PrivilegeMaster)
                .HasColumnName("PrivilegeMaster")
                .IsRequired();
            Property(t => t.PrivilegeMasterValue)
                .HasColumnName("PrivilegeMasterValue")
                .HasMaxLength(150)
                .IsRequired();
            Property(t => t.PrivilegeAccess)
                .HasColumnName("PrivilegeAccess")
                .IsRequired();
            Property(t => t.PrivilegeAccessValue)
                .HasColumnName("PrivilegeAccessValue")
                .HasMaxLength(150)
                .IsRequired();
            Property(t => t.PrivilegeOperation)
                .HasColumnName("PrivilegeOperation")
                .IsRequired();
            Property(t => t.CreationTime)
                .HasColumnName("CreationTime")
                .IsRequired();

            // Relationships

            InitializeMapping();
        }
    }
}
