//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using Abp.EntityFramework;
using CodeSmith.Abp.Template.Test.Core;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.EntityFramework
{
    public partial class BsuseroperatelogMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Bsuseroperatelog>
    {
        public BsuseroperatelogMap()
        {
            // table
            ToTable("bsuseroperatelog");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.MenuId)
                .HasColumnName("MenuId")
                .IsOptional();
            Property(t => t.ButtonId)
                .HasColumnName("ButtonId")
                .IsOptional();
            Property(t => t.OperateType)
                .HasColumnName("OperateType")
                .IsOptional();
            Property(t => t.OperateData)
                .HasColumnName("OperateData")
                .IsOptional();
            Property(t => t.CreatorUserId)
                .HasColumnName("CreatorUserId")
                .IsOptional();
            Property(t => t.CreationTime)
                .HasColumnName("CreationTime")
                .IsRequired();
            Property(t => t.Remarks)
                .HasColumnName("Remarks")
                .HasMaxLength(1500)
                .IsOptional();

            // Relationships
            HasOptional(t => t.ButtonBsbutton)
                .WithMany(t => t.ButtonBsuseroperatelogs)
                .HasForeignKey(d => d.ButtonId)
                .WillCascadeOnDelete(false);
            HasOptional(t => t.MenuBsmenu)
                .WithMany(t => t.MenuBsuseroperatelogs)
                .HasForeignKey(d => d.MenuId)
                .WillCascadeOnDelete(false);
            HasOptional(t => t.CreatorUserBsuser)
                .WithMany(t => t.CreatorUserBsuseroperatelogs)
                .HasForeignKey(d => d.CreatorUserId)
                .WillCascadeOnDelete(false);

            InitializeMapping();
        }
    }
}
