//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using Abp.EntityFramework;
using CodeSmith.Abp.Template.Test.Core;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.EntityFramework
{
    public partial class BsuserMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Bsuser>
    {
        public BsuserMap()
        {
            // table
            ToTable("bsuser");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.UserName)
                .HasColumnName("UserName")
                .HasMaxLength(150)
                .IsRequired();
            Property(t => t.Account)
                .HasColumnName("Account")
                .HasMaxLength(150)
                .IsRequired();
            Property(t => t.PassWord)
                .HasColumnName("PassWord")
                .HasMaxLength(765)
                .IsRequired();
            Property(t => t.IsAction)
                .HasColumnName("IsAction")
                .IsRequired();
            Property(t => t.IsAdmin)
                .HasColumnName("IsAdmin")
                .IsRequired();
            Property(t => t.IsDeleted)
                .HasColumnName("IsDeleted")
                .IsRequired();
            Property(t => t.CreationTime)
                .HasColumnName("CreationTime")
                .IsRequired();
            Property(t => t.LastLoginDate)
                .HasColumnName("LastLoginDate")
                .IsOptional();
            Property(t => t.LastRole)
                .HasColumnName("LastRole")
                .IsOptional();

            // Relationships
            HasOptional(t => t.LastRoleBsrole)
                .WithMany(t => t.LastRoleBsusers)
                .HasForeignKey(d => d.LastRole)
                .WillCascadeOnDelete(false);

            InitializeMapping();
        }
    }
}
