//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using Abp.EntityFramework;
using CodeSmith.Abp.Template.Test.Core;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.EntityFramework
{
    public partial class BsuserfeedbackMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Bsuserfeedback>
    {
        public BsuserfeedbackMap()
        {
            // table
            ToTable("bsuserfeedback");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.Title)
                .HasColumnName("Title")
                .HasMaxLength(150)
                .IsOptional();
            Property(t => t.Contents)
                .HasColumnName("Contents")
                .HasMaxLength(765)
                .IsOptional();
            Property(t => t.FeedbackType)
                .HasColumnName("FeedbackType")
                .IsRequired();
            Property(t => t.IsDeleted)
                .HasColumnName("IsDeleted")
                .IsRequired();
            Property(t => t.FeedbackImg)
                .HasColumnName("FeedbackImg")
                .HasMaxLength(1500)
                .IsOptional();
            Property(t => t.CreatorUserId)
                .HasColumnName("CreatorUserId")
                .IsOptional();
            Property(t => t.CreationTime)
                .HasColumnName("CreationTime")
                .IsRequired();

            // Relationships
            HasOptional(t => t.CreatorUserBsuser)
                .WithMany(t => t.CreatorUserBsuserfeedbacks)
                .HasForeignKey(d => d.CreatorUserId)
                .WillCascadeOnDelete(false);

            InitializeMapping();
        }
    }
}
