//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using Abp.EntityFramework;
using CodeSmith.Abp.Template.Test.Core;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.EntityFramework
{
    public partial class CmacquisitionlogMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Cmacquisitionlog>
    {
        public CmacquisitionlogMap()
        {
            // table
            ToTable("cmacquisitionlog");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.ObjectName)
                .HasColumnName("ObjectName")
                .HasMaxLength(600)
                .IsRequired();
            Property(t => t.ObjectCode)
                .HasColumnName("ObjectCode")
                .HasMaxLength(600)
                .IsRequired();
            Property(t => t.Contents)
                .HasColumnName("Contents")
                .IsOptional();
            Property(t => t.CreationTime)
                .HasColumnName("CreationTime")
                .IsRequired();

            // Relationships

            InitializeMapping();
        }
    }
}
