//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using Abp.EntityFramework;
using CodeSmith.Abp.Template.Test.Core;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.EntityFramework
{
    public partial class TfdrillingMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Tfdrilling>
    {
        public TfdrillingMap()
        {
            // table
            ToTable("tfdrilling");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.AddressId)
                .HasColumnName("AddressId")
                .IsRequired();
            Property(t => t.DrillingName)
                .HasColumnName("DrillingName")
                .HasMaxLength(765)
                .IsRequired();
            Property(t => t.IsDeleted)
                .HasColumnName("IsDeleted")
                .IsRequired();
            Property(t => t.CreationTime)
                .HasColumnName("CreationTime")
                .IsRequired();

            // Relationships
            HasRequired(t => t.AddressCmaddress)
                .WithMany(t => t.AddressTfdrillings)
                .HasForeignKey(d => d.AddressId)
                .WillCascadeOnDelete(false);

            InitializeMapping();
        }
    }
}
