//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using Abp.EntityFramework;
using CodeSmith.Abp.Template.Test.Core;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.EntityFramework
{
    public partial class TfmonitorabnormalMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Tfmonitorabnormal>
    {
        public TfmonitorabnormalMap()
        {
            // table
            ToTable("tfmonitorabnormal");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.Exception)
                .HasColumnName("Exception")
                .HasMaxLength(765)
                .IsOptional();
            Property(t => t.AbnormalContext)
                .HasColumnName("AbnormalContext")
                .HasMaxLength(765)
                .IsOptional();
            Property(t => t.AddressName)
                .HasColumnName("AddressName")
                .HasMaxLength(765)
                .IsOptional();
            Property(t => t.StartTime)
                .HasColumnName("StartTime")
                .IsOptional();
            Property(t => t.EndTime)
                .HasColumnName("EndTime")
                .IsOptional();
            Property(t => t.MaxAlarmValue)
                .HasColumnName("MaxAlarmValue")
                .HasMaxLength(150)
                .IsOptional();
            Property(t => t.MaxAlarmTime)
                .HasColumnName("MaxAlarmTime")
                .IsOptional();
            Property(t => t.Reason)
                .HasColumnName("Reason")
                .HasMaxLength(765)
                .IsOptional();
            Property(t => t.Remarks)
                .HasColumnName("Remarks")
                .HasMaxLength(765)
                .IsOptional();

            // Relationships

            InitializeMapping();
        }
    }
}
