//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using Abp.EntityFramework;
using CodeSmith.Abp.Template.Test.Core;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.EntityFramework
{
    public partial class TfmonitoranalogMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Tfmonitoranalog>
    {
        public TfmonitoranalogMap()
        {
            // table
            ToTable("tfmonitoranalog");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.AddressId)
                .HasColumnName("AddressId")
                .IsRequired();
            Property(t => t.SysType)
                .HasColumnName("SysType")
                .IsRequired();
            Property(t => t.MonitorType)
                .HasColumnName("MonitorType")
                .IsRequired();
            Property(t => t.MaxValue)
                .HasColumnName("MaxValue")
                .HasPrecision(18, 4)
                .IsOptional();
            Property(t => t.MaxMomentValue)
                .HasColumnName("MaxMomentValue")
                .HasMaxLength(150)
                .IsOptional();
            Property(t => t.MinValue)
                .HasColumnName("MinValue")
                .HasPrecision(18, 4)
                .IsOptional();
            Property(t => t.MinMomentValue)
                .HasColumnName("MinMomentValue")
                .HasMaxLength(150)
                .IsOptional();
            Property(t => t.DailyAverageValue)
                .HasColumnName("DailyAverageValue")
                .HasPrecision(18, 4)
                .IsOptional();
            Property(t => t.OutCount)
                .HasColumnName("OutCount")
                .IsOptional();
            Property(t => t.CreationTime)
                .HasColumnName("CreationTime")
                .IsRequired();
            Property(t => t.CollectionTime)
                .HasColumnName("CollectionTime")
                .IsRequired();
            Property(t => t.Remarks)
                .HasColumnName("Remarks")
                .HasMaxLength(765)
                .IsOptional();

            // Relationships
            HasRequired(t => t.AddressCmaddress)
                .WithMany(t => t.AddressTfmonitoranalogs)
                .HasForeignKey(d => d.AddressId)
                .WillCascadeOnDelete(false);

            InitializeMapping();
        }
    }
}
