//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using Abp.EntityFramework;
using CodeSmith.Abp.Template.Test.Core;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.EntityFramework
{
    public partial class TfproofreadMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Tfproofread>
    {
        public TfproofreadMap()
        {
            // table
            ToTable("tfproofread");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.AddressId)
                .HasColumnName("AddressId")
                .IsRequired();
            Property(t => t.ProofType)
                .HasColumnName("ProofType")
                .IsRequired();
            Property(t => t.K)
                .HasColumnName("K")
                .HasPrecision(18, 6)
                .IsRequired();
            Property(t => t.Ch4)
                .HasColumnName("CH4")
                .HasPrecision(18, 6)
                .IsRequired();
            Property(t => t.H)
                .HasColumnName("H")
                .HasPrecision(18, 6)
                .IsRequired();
            Property(t => t.T)
                .HasColumnName("T")
                .HasPrecision(18, 6)
                .IsRequired();
            Property(t => t.Kpa)
                .HasColumnName("Kpa")
                .HasPrecision(18, 6)
                .IsRequired();
            Property(t => t.Qh)
                .HasColumnName("QH")
                .HasPrecision(18, 6)
                .IsRequired();
            Property(t => t.Qb)
                .HasColumnName("QB")
                .HasPrecision(18, 6)
                .IsRequired();
            Property(t => t.CreationTime)
                .HasColumnName("CreationTime")
                .IsRequired();
            Property(t => t.CollectionTime)
                .HasColumnName("CollectionTime")
                .IsRequired();
            Property(t => t.Remarks)
                .HasColumnName("Remarks")
                .HasMaxLength(765)
                .IsOptional();

            // Relationships
            HasRequired(t => t.AddressCmaddress)
                .WithMany(t => t.AddressTfproofreads)
                .HasForeignKey(d => d.AddressId)
                .WillCascadeOnDelete(false);

            InitializeMapping();
        }
    }
}
