//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using Abp.EntityFramework;
using CodeSmith.Abp.Template.Test.Core;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.EntityFramework
{
    public partial class WsgasMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Wsgas>
    {
        public WsgasMap()
        {
            // table
            ToTable("wsgas");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.AddressId)
                .HasColumnName("AddressId")
                .IsRequired();
            Property(t => t.AirVolume)
                .HasColumnName("AirVolume")
                .IsRequired();
            Property(t => t.WorkingFaceCH4)
                .HasColumnName("WorkingFaceCH4")
                .IsRequired();
            Property(t => t.UpperCornerCH4)
                .HasColumnName("UpperCornerCH4")
                .IsRequired();
            Property(t => t.GoafCH4)
                .HasColumnName("GoafCH4")
                .IsRequired();
            Property(t => t.BackRomanticAvg)
                .HasColumnName("BackRomanticAvg")
                .IsRequired();
            Property(t => t.BackRomanticMax)
                .HasColumnName("BackRomanticMax")
                .IsRequired();
            Property(t => t.MaxGushGas)
                .HasColumnName("MaxGushGas")
                .IsRequired();
            Property(t => t.AverageExhaustAir)
                .HasColumnName("AverageExhaustAir")
                .IsRequired();
            Property(t => t.AverageGushGas)
                .HasColumnName("AverageGushGas")
                .IsRequired();
            Property(t => t.PureFlow)
                .HasColumnName("PureFlow")
                .IsRequired();
            Property(t => t.CreationTime)
                .HasColumnName("CreationTime")
                .IsRequired();
            Property(t => t.CollectionTime)
                .HasColumnName("CollectionTime")
                .IsRequired();

            // Relationships
            HasRequired(t => t.AddressCmaddress)
                .WithMany(t => t.AddressWsgas)
                .HasForeignKey(d => d.AddressId)
                .WillCascadeOnDelete(false);

            InitializeMapping();
        }
    }
}
