//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using Abp.EntityFramework;
using CodeSmith.Abp.Template.Test.Core;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.EntityFramework
{
    public partial class WsworkMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Wswork>
    {
        public WsworkMap()
        {
            // table
            ToTable("wswork");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.CollectionTime)
                .HasColumnName("CollectionTime")
                .IsRequired();
            Property(t => t.SameDay)
                .HasColumnName("SameDay")
                .HasPrecision(18, 4)
                .IsRequired();
            Property(t => t.Accumulative)
                .HasColumnName("Accumulative")
                .HasPrecision(18, 4)
                .IsRequired();
            Property(t => t.MultipleWork)
                .HasColumnName("MultipleWork")
                .IsRequired();
            Property(t => t.Project)
                .HasColumnName("Project")
                .IsRequired();
            Property(t => t.SystemStatus)
                .HasColumnName("SystemStatus")
                .IsRequired();
            Property(t => t.Focus)
                .HasColumnName("Focus")
                .IsRequired();
            Property(t => t.Remarks)
                .HasColumnName("Remarks")
                .IsRequired();

            // Relationships

            InitializeMapping();
        }
    }
}
