//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using Abp.EntityFramework;
using CodeSmith.Abp.Template.Test.Core;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.EntityFramework
{
    public partial class ZtconstructionsiteMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Ztconstructionsite>
    {
        public ZtconstructionsiteMap()
        {
            // table
            ToTable("ztconstructionsite");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.ConstructionSiteName)
                .HasColumnName("ConstructionSiteName")
                .HasMaxLength(765)
                .IsRequired();
            Property(t => t.LastDrillingRig)
                .HasColumnName("LastDrillingRig")
                .HasMaxLength(150)
                .IsOptional();
            Property(t => t.LastMonthlyPlan)
                .HasColumnName("LastMonthlyPlan")
                .IsOptional();
            Property(t => t.LastTeam)
                .HasColumnName("LastTeam")
                .HasMaxLength(150)
                .IsOptional();
            Property(t => t.PoreSize)
                .HasColumnName("PoreSize")
                .HasPrecision(18, 1)
                .IsOptional();
            Property(t => t.State)
                .HasColumnName("State")
                .IsRequired();
            Property(t => t.IsDeleted)
                .HasColumnName("IsDeleted")
                .IsRequired();
            Property(t => t.StartMonthlyPlan)
                .HasColumnName("StartMonthlyPlan")
                .IsRequired();
            Property(t => t.CreationTime)
                .HasColumnName("CreationTime")
                .IsRequired();
            Property(t => t.Remarks)
                .HasColumnName("Remarks")
                .HasMaxLength(765)
                .IsOptional();

            // Relationships

            InitializeMapping();
        }
    }
}
