//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using Abp.EntityFramework;
using CodeSmith.Abp.Template.Test.Core;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.EntityFramework
{
    public partial class ZtfieldiinspectionMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Ztfieldiinspection>
    {
        public ZtfieldiinspectionMap()
        {
            // table
            ToTable("ztfieldiinspection");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.Address)
                .HasColumnName("Address")
                .HasMaxLength(765)
                .IsRequired();
            Property(t => t.DrillingField)
                .HasColumnName("DrillingField")
                .HasMaxLength(765)
                .IsOptional();
            Property(t => t.Distance)
                .HasColumnName("Distance")
                .HasMaxLength(765)
                .IsOptional();
            Property(t => t.Drainage)
                .HasColumnName("Drainage")
                .HasMaxLength(765)
                .IsOptional();
            Property(t => t.Method)
                .HasColumnName("Method")
                .HasMaxLength(765)
                .IsOptional();
            Property(t => t.Concentration)
                .HasColumnName("Concentration")
                .HasPrecision(18, 4)
                .IsOptional();
            Property(t => t.MixedFlow)
                .HasColumnName("MixedFlow")
                .HasPrecision(18, 4)
                .IsOptional();
            Property(t => t.PureFlow)
                .HasColumnName("PureFlow")
                .HasPrecision(18, 4)
                .IsOptional();
            Property(t => t.Temperature)
                .HasColumnName("Temperature")
                .HasPrecision(18, 4)
                .IsOptional();
            Property(t => t.CreationTime)
                .HasColumnName("CreationTime")
                .IsRequired();
            Property(t => t.CollectionTime)
                .HasColumnName("CollectionTime")
                .IsRequired();
            Property(t => t.Remarks)
                .HasColumnName("Remarks")
                .IsOptional();

            // Relationships

            InitializeMapping();
        }
    }
}
