//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using Abp.EntityFramework;
using CodeSmith.Abp.Template.Test.Core;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.EntityFramework
{
    public partial class ZtporeplateMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Ztporeplate>
    {
        public ZtporeplateMap()
        {
            // table
            ToTable("ztporeplate");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.AddressId)
                .HasColumnName("AddressId")
                .IsRequired();
            Property(t => t.Temperature)
                .HasColumnName("Temperature")
                .HasPrecision(18, 4)
                .IsOptional();
            Property(t => t.OrificePlateCoefficient)
                .HasColumnName("OrificePlateCoefficient")
                .HasMaxLength(765)
                .IsOptional();
            Property(t => t.Concentration)
                .HasColumnName("Concentration")
                .HasPrecision(18, 4)
                .IsOptional();
            Property(t => t.DifferentialPressure)
                .HasColumnName("DifferentialPressure")
                .HasPrecision(18, 4)
                .IsOptional();
            Property(t => t.NegativePressure)
                .HasColumnName("NegativePressure")
                .HasPrecision(18, 4)
                .IsOptional();
            Property(t => t.MixedFlow)
                .HasColumnName("MixedFlow")
                .HasPrecision(18, 4)
                .IsOptional();
            Property(t => t.PureFlow)
                .HasColumnName("PureFlow")
                .HasPrecision(18, 4)
                .IsOptional();
            Property(t => t.Remarks)
                .HasColumnName("Remarks")
                .HasMaxLength(765)
                .IsOptional();
            Property(t => t.CollectionTime)
                .HasColumnName("CollectionTime")
                .IsRequired();
            Property(t => t.CreationTime)
                .HasColumnName("CreationTime")
                .IsRequired();

            // Relationships
            HasRequired(t => t.AddressCmaddress)
                .WithMany(t => t.AddressZtporeplates)
                .HasForeignKey(d => d.AddressId)
                .WillCascadeOnDelete(false);

            InitializeMapping();
        }
    }
}
