//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Abp.Application.Services.Dto;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Application
{
    public partial class BsmenuDto : IEntityDto<int>, IInputDto, IOutputDto
    {
        /// <summary>
        /// 
        /// </summary>    
        public int Id { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string MenuText { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string MenuUrl { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int Sort { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? ParentMenuId { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string ParentMenuIds { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public bool IsMain { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public bool IsInline { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public bool IsActive { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string OpenEvent { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string CloseEvent { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CreationTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Remark { get; set; }

    }
}

