//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     请不要对该文件内容进行修改。如果重新生成代码，文件内容将被覆盖。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Core
{
    public partial class Zthole : IEntity<int>,IHasCreationTime
    {
        public Zthole()
        {
        }
        
        public bool IsTransient()
        {
            return EqualityComparer<int>.Default.Equals(this.Id, default(int));
        }

        /// <summary>
        /// 
        /// </summary>    
        public int Id { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int ConstructionSiteId { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string DrillingRig { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? DayStage { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? DrillingFootage { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? DayTotal { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? MonthTotal { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? CurrentMonthPlan { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string PersonInCharge { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? CurrentPeopleNum { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string No { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? HoleType { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? PoreSize { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Position { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? DipAngle { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? DesignHoleDepth { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? Coal { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? Rock { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string ConstructionSituation { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string SpaceBefore { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int IsEndHole { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Team { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CollectionTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CreationTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Remarks { get; set; }

        public virtual Ztconstructionsite ConstructionSiteZtconstructionsite { get; set; }
    }
}