//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Abp.Application.Services.Dto;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Application
{
    public partial class GetWsclosedwallfeaturePageInput : DefaultPagedResultRequest
    {
        
        /// <summary>
        /// 
        /// </summary>    
        public int? Id { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? AddressId { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? LocationType { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? Co { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? Co2 { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? C2h4 { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? Ch4 { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? C2h6 { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? C2h2 { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? O2 { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? N2 { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? T { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Statistic { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? Nitrogen { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? Inhibitor { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? Grouting { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Other { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string RiskSituation { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime? CreationTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime? CollectionTime { get; set; }
    }
}

