//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     请不要对该文件内容进行修改。如果重新生成代码，文件内容将被覆盖。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Core
{
    public partial class Bsdictionary : IEntity<int>,IAudited,ICreationAudited,IHasCreationTime,IModificationAudited,IPassivable,ISoftDelete
    {
        public Bsdictionary()
        {
            ParentBsdictionaries = new List<Bsdictionary>();
            ParentBsdictionaries1 = new List<Bsdictionary>();
        }
        
        public bool IsTransient()
        {
            return EqualityComparer<int>.Default.Equals(this.Id, default(int));
        }

        /// <summary>
        /// 
        /// </summary>    
        public int Id { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? ParentId { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string ParentIds { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string DictionaryKey { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string DictionaryName { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string DictionaryValue { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public bool IsActive { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public bool IsDeleted { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public bool IsGroup { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public long? CreatorUserId { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CreationTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public long? LastModifierUserId { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime? LastModificationTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int Sort { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Remarks { get; set; }

        public virtual Bsdictionary ParentBsdictionary { get; set; }
        public virtual ICollection<Bsdictionary> ParentBsdictionaries { get; set; }
        public virtual Bsuser CreatorUserBsuser { get; set; }
        public virtual Bsuser LastModifierUserBsuser { get; set; }
        public virtual Bsdictionary ParentBsdictionary1 { get; set; }
        public virtual ICollection<Bsdictionary> ParentBsdictionaries1 { get; set; }
    }
}