//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     请不要对该文件内容进行修改。如果重新生成代码，文件内容将被覆盖。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Core
{
    public partial class Cmsensorinfo : IEntity<int>,IHasCreationTime
    {
        public Cmsensorinfo()
        {
            SensorCmaddressconfigs = new List<Cmaddressconfig>();
            SensorTfclosedwallfeatures = new List<Tfclosedwallfeature>();
        }
        
        public bool IsTransient()
        {
            return EqualityComparer<int>.Default.Equals(this.Id, default(int));
        }

        /// <summary>
        /// 
        /// </summary>    
        public int Id { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int SysType { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string SysTypeName { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int ObjectType { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string ObjectTypeName { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string ObjectName { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Code { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public bool IsUse { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CreationTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Remarks { get; set; }

        public virtual ICollection<Cmaddressconfig> SensorCmaddressconfigs { get; set; }
        public virtual ICollection<Tfclosedwallfeature> SensorTfclosedwallfeatures { get; set; }
    }
}