//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     请不要对该文件内容进行修改。如果重新生成代码，文件内容将被覆盖。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Core
{
    public partial class Wsgas : IEntity<int>,IHasCreationTime
    {
        public Wsgas()
        {
        }
        
        public bool IsTransient()
        {
            return EqualityComparer<int>.Default.Equals(this.Id, default(int));
        }

        /// <summary>
        /// 
        /// </summary>    
        public int Id { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int AddressId { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public double AirVolume { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public double WorkingFaceCH4 { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public double UpperCornerCH4 { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public double GoafCH4 { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public double BackRomanticAvg { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public double BackRomanticMax { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public double MaxGushGas { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public double AverageExhaustAir { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public double AverageGushGas { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public double PureFlow { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CreationTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CollectionTime { get; set; }

        public virtual Cmaddress AddressCmaddress { get; set; }
    }
}