//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Abp.Application.Services.Dto;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Application
{
    public partial class GetTfproofreadPageInput : DefaultPagedResultRequest
    {
        
        /// <summary>
        /// 
        /// </summary>    
        public int? Id { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? AddressId { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? ProofType { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? K { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? Ch4 { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? H { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? T { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? Kpa { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? Qh { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? Qb { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime? CreationTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime? CollectionTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Remarks { get; set; }
    }
}

