//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     请不要对该文件内容进行修改。如果重新生成代码，文件内容将被覆盖。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Core
{
    public partial class Tfkindlefirewall : IEntity<int>,IHasCreationTime
    {
        public Tfkindlefirewall()
        {
        }
        
        public bool IsTransient()
        {
            return EqualityComparer<int>.Default.Equals(this.Id, default(int));
        }

        /// <summary>
        /// 
        /// </summary>    
        public int Id { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int EnclosedWallLedgerId { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal GasConcentration { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal COConcentration { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? CO2Concentration { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal Temperature { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal O2Concentration { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal OutsideGasConcentration { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? OutsideCO2Concentration { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? OutsideCOConcentration { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? OutsideTConcentration { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal DifferentialPressure { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal WaterTemperature { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public bool IsSensor { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public bool IsBeamTube { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public bool IsCOSensor { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public bool IsDrainage { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CreationTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CollectionTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Remarks { get; set; }

        public virtual Tfenclosedwallledger EnclosedWallLedgerTfenclosedwallledger { get; set; }
    }
}