//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     请不要对该文件内容进行修改。如果重新生成代码，文件内容将被覆盖。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Core
{
    public partial class Bsuser : IEntity<long>,IHasCreationTime,ISoftDelete
    {
        public Bsuser()
        {
            CreatorUserBsdictionaries = new List<Bsdictionary>();
            LastModifierUserBsdictionaries = new List<Bsdictionary>();
            CreatorUserBsuserfeedbacks = new List<Bsuserfeedback>();
            CreatorUserBsuseroperatelogs = new List<Bsuseroperatelog>();
        }
        
        public bool IsTransient()
        {
            return EqualityComparer<long>.Default.Equals(this.Id, default(long));
        }

        /// <summary>
        /// 
        /// </summary>    
        public long Id { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string UserName { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Account { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string PassWord { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public bool IsAction { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public bool IsAdmin { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public bool IsDeleted { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CreationTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime? LastLoginDate { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? LastRole { get; set; }

        public virtual ICollection<Bsdictionary> CreatorUserBsdictionaries { get; set; }
        public virtual ICollection<Bsdictionary> LastModifierUserBsdictionaries { get; set; }
        public virtual Bsrole LastRoleBsrole { get; set; }
        public virtual ICollection<Bsuserfeedback> CreatorUserBsuserfeedbacks { get; set; }
        public virtual ICollection<Bsuseroperatelog> CreatorUserBsuseroperatelogs { get; set; }
    }
}