//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Abp.Application.Services.Dto;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Application
{
    public partial class GetZtholePageInput : DefaultPagedResultRequest
    {
        
        /// <summary>
        /// 
        /// </summary>    
        public int? Id { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? ConstructionSiteId { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string DrillingRig { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? DayStage { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? DrillingFootage { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? DayTotal { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? MonthTotal { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? CurrentMonthPlan { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string PersonInCharge { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? CurrentPeopleNum { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string No { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? HoleType { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? PoreSize { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Position { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? DipAngle { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? DesignHoleDepth { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? Coal { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? Rock { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string ConstructionSituation { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string SpaceBefore { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? IsEndHole { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Team { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime? CollectionTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime? CreationTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Remarks { get; set; }
    }
}

