//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     请不要对该文件内容进行修改。如果重新生成代码，文件内容将被覆盖。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Core
{
    public partial class Wsoutburstprevention : IEntity<int>,IHasCreationTime
    {
        public Wsoutburstprevention()
        {
        }
        
        public bool IsTransient()
        {
            return EqualityComparer<int>.Default.Equals(this.Id, default(int));
        }

        /// <summary>
        /// 
        /// </summary>    
        public int Id { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string AddressName { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string MeasuringPoint { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public double? K1 { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public double? Smax { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? H2 { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string T2 { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Type { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int AllowFootage { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public bool OverWhether { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public bool IsShow { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string FaceSituation { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string ReasonAnalysis { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CreationTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CollectionTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Hole { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime? OpenHole { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime? FinalHole { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Construction { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Recorder { get; set; }

    }
}