//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Abp.Application.Services.Dto;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Application
{
    public partial class TfenclosedwallledgerDto : IEntityDto<int>, IInputDto, IOutputDto
    {
        /// <summary>
        /// 
        /// </summary>    
        public int Id { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string MiningArea { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int EnclosedWallNo { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string EnclosedWallName { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Place { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Lithology { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string SupportForm { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime? SealOffDate { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string SystemStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string GoafStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string TunnelLlength { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string MaterialQuality { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Thickness { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CreationTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public bool IsClose { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Remarks { get; set; }

    }
}

