//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Abp.Application.Services.Dto;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Application
{
    public partial class TfkeyheadDto : IEntityDto<int>, IInputDto, IOutputDto
    {
        /// <summary>
        /// 
        /// </summary>    
        public int Id { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Address { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string SupportingMethod { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string SectionDescription { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string EyeNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string DeepEye { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string MouthGas { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string GasAfterGun { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string AllowFootage { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string ExcessSize { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string ImgUrl { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CollectionTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CreationTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Remarks { get; set; }

    }
}

