//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     请不要对该文件内容进行修改。如果重新生成代码，文件内容将被覆盖。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Core
{
    public partial class Ztconstructionsite : IEntity<int>,IHasCreationTime,ISoftDelete
    {
        public Ztconstructionsite()
        {
            ConstructionSiteZtholes = new List<Zthole>();
        }
        
        public bool IsTransient()
        {
            return EqualityComparer<int>.Default.Equals(this.Id, default(int));
        }

        /// <summary>
        /// 
        /// </summary>    
        public int Id { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string ConstructionSiteName { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string LastDrillingRig { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? LastMonthlyPlan { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string LastTeam { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public decimal? PoreSize { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int State { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public bool IsDeleted { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int StartMonthlyPlan { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CreationTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Remarks { get; set; }

        public virtual ICollection<Zthole> ConstructionSiteZtholes { get; set; }
    }
}