//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     请不要对该文件内容进行修改。如果重新生成代码，文件内容将被覆盖。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Core
{
    public partial class Bsmenubutton : IEntity<int>,IAudited,ICreationAudited,IHasCreationTime,IModificationAudited,IPassivable
    {
        public Bsmenubutton()
        {
        }
        
        public bool IsTransient()
        {
            return EqualityComparer<int>.Default.Equals(this.Id, default(int));
        }

        /// <summary>
        /// 
        /// </summary>    
        public int Id { get; set; }
        /// <summary>
        /// 
        /// </summary>    
<<<<<<< HEAD
<<<<<<< HEAD
        public int ButtonId { get; set; }
=======
        public int? ButtonId { get; set; }
>>>>>>> 3200a17c688e0da9fa0413a47e2920c458aa7c50
=======
        public int? ButtonId { get; set; }
>>>>>>> 3200a17c688e0da9fa0413a47e2920c458aa7c50
        /// <summary>
        /// 
        /// </summary>    
        public int MenuId { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string ButtonText { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string RunEvent { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string IconClass { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public bool IsActive { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int Sort { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime? LastModificationTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public long? LastModifierUserId { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public long? CreatorUserId { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CreationTime { get; set; }

        public virtual Bsbutton ButtonBsbutton { get; set; }
        public virtual Bsmenu MenuBsmenu { get; set; }
    }
}