//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Abp.Application.Services.Dto;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Application
{
    public partial class WsoutburstpreventionDto : IEntityDto<int>, IInputDto, IOutputDto
    {
        /// <summary>
        /// 
        /// </summary>    
        public int Id { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string AddressName { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string MeasuringPoint { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public double? K1 { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public double? Smax { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int? H2 { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string T2 { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Type { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int AllowFootage { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public bool OverWhether { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public bool IsShow { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string FaceSituation { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string ReasonAnalysis { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CreationTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CollectionTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Hole { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime? OpenHole { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime? FinalHole { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Construction { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Recorder { get; set; }

    }
}

