//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Abp.Application.Services.Dto;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;
using AutoMapper;
using CodeSmith.Abp.Template.Test.Core;

namespace CodeSmith.Abp.Template.Test.Application
{
    internal static partial class DtoMappings
    {
        public static void Map()
        {
            //I specified mapping for AssignedPersonId since NHibernate does not fill Task.AssignedPersonId
            //If you will just use EF, then you can remove ForMember definition.
            Mapper.CreateMap<Bsbutton,  BsbuttonDto>();
            Mapper.CreateMap<BsbuttonDto,  Bsbutton>();
            Mapper.CreateMap<Bsdictionary,  BsdictionaryDto>();
            Mapper.CreateMap<BsdictionaryDto,  Bsdictionary>();
            Mapper.CreateMap<Bsmenu,  BsmenuDto>();
            Mapper.CreateMap<BsmenuDto,  Bsmenu>();
            Mapper.CreateMap<Bsmenubutton,  BsmenubuttonDto>();
            Mapper.CreateMap<BsmenubuttonDto,  Bsmenubutton>();
            Mapper.CreateMap<Bspermission,  BspermissionDto>();
            Mapper.CreateMap<BspermissionDto,  Bspermission>();
            Mapper.CreateMap<Bsrole,  BsroleDto>();
            Mapper.CreateMap<BsroleDto,  Bsrole>();
            Mapper.CreateMap<Bsuser,  BsuserDto>();
            Mapper.CreateMap<BsuserDto,  Bsuser>();
            Mapper.CreateMap<Bsuserfeedback,  BsuserfeedbackDto>();
            Mapper.CreateMap<BsuserfeedbackDto,  Bsuserfeedback>();
            Mapper.CreateMap<Bsuseroperatelog,  BsuseroperatelogDto>();
            Mapper.CreateMap<BsuseroperatelogDto,  Bsuseroperatelog>();
            Mapper.CreateMap<Cmacquisitionlog,  CmacquisitionlogDto>();
            Mapper.CreateMap<CmacquisitionlogDto,  Cmacquisitionlog>();
            Mapper.CreateMap<Cmaddress,  CmaddressDto>();
            Mapper.CreateMap<CmaddressDto,  Cmaddress>();
            Mapper.CreateMap<Cmaddressconfig,  CmaddressconfigDto>();
            Mapper.CreateMap<CmaddressconfigDto,  Cmaddressconfig>();
            Mapper.CreateMap<Cmdictionaryconfig,  CmdictionaryconfigDto>();
            Mapper.CreateMap<CmdictionaryconfigDto,  Cmdictionaryconfig>();
            Mapper.CreateMap<Cmsensorinfo,  CmsensorinfoDto>();
            Mapper.CreateMap<CmsensorinfoDto,  Cmsensorinfo>();
            Mapper.CreateMap<Tfclosedwallfacilities,  TfclosedwallfacilitiesDto>();
            Mapper.CreateMap<TfclosedwallfacilitiesDto,  Tfclosedwallfacilities>();
            Mapper.CreateMap<Tfclosedwallfeature,  TfclosedwallfeatureDto>();
            Mapper.CreateMap<TfclosedwallfeatureDto,  Tfclosedwallfeature>();
            Mapper.CreateMap<Tfdrilling,  TfdrillingDto>();
            Mapper.CreateMap<TfdrillingDto,  Tfdrilling>();
            Mapper.CreateMap<Tfenclosedwallledger,  TfenclosedwallledgerDto>();
            Mapper.CreateMap<TfenclosedwallledgerDto,  Tfenclosedwallledger>();
            Mapper.CreateMap<Tfgasdrainage,  TfgasdrainageDto>();
            Mapper.CreateMap<TfgasdrainageDto,  Tfgasdrainage>();
            Mapper.CreateMap<Tfgasdrilling,  TfgasdrillingDto>();
            Mapper.CreateMap<TfgasdrillingDto,  Tfgasdrilling>();
            Mapper.CreateMap<Tfkeyhead,  TfkeyheadDto>();
            Mapper.CreateMap<TfkeyheadDto,  Tfkeyhead>();
            Mapper.CreateMap<Tfkindlefirewall,  TfkindlefirewallDto>();
            Mapper.CreateMap<TfkindlefirewallDto,  Tfkindlefirewall>();
            Mapper.CreateMap<Tfmonitorabnormal,  TfmonitorabnormalDto>();
            Mapper.CreateMap<TfmonitorabnormalDto,  Tfmonitorabnormal>();
            Mapper.CreateMap<Tfmonitoranalog,  TfmonitoranalogDto>();
            Mapper.CreateMap<TfmonitoranalogDto,  Tfmonitoranalog>();
            Mapper.CreateMap<Tfpointclosedwall,  TfpointclosedwallDto>();
            Mapper.CreateMap<TfpointclosedwallDto,  Tfpointclosedwall>();
            Mapper.CreateMap<Tfproofread,  TfproofreadDto>();
            Mapper.CreateMap<TfproofreadDto,  Tfproofread>();
            Mapper.CreateMap<Tfworkingface,  TfworkingfaceDto>();
            Mapper.CreateMap<TfworkingfaceDto,  Tfworkingface>();
            Mapper.CreateMap<Wsclosedwallfeature,  WsclosedwallfeatureDto>();
            Mapper.CreateMap<WsclosedwallfeatureDto,  Wsclosedwallfeature>();
            Mapper.CreateMap<Wsgas,  WsgasDto>();
            Mapper.CreateMap<WsgasDto,  Wsgas>();
            Mapper.CreateMap<Wsoutburstprevention,  WsoutburstpreventionDto>();
            Mapper.CreateMap<WsoutburstpreventionDto,  Wsoutburstprevention>();
            Mapper.CreateMap<Wswork,  WsworkDto>();
            Mapper.CreateMap<WsworkDto,  Wswork>();
            Mapper.CreateMap<Ztconstructionsite,  ZtconstructionsiteDto>();
            Mapper.CreateMap<ZtconstructionsiteDto,  Ztconstructionsite>();
            Mapper.CreateMap<Ztfieldiinspection,  ZtfieldiinspectionDto>();
            Mapper.CreateMap<ZtfieldiinspectionDto,  Ztfieldiinspection>();
            Mapper.CreateMap<Zthole,  ZtholeDto>();
            Mapper.CreateMap<ZtholeDto,  Zthole>();
            Mapper.CreateMap<Ztporeplate,  ZtporeplateDto>();
            Mapper.CreateMap<ZtporeplateDto,  Ztporeplate>();
            InitializeMapping();
        }
    }
}