//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using Abp.Domain.Repositories;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Core
{  
    public partial interface IBsuseroperatelogRepository : IRepository<Bsuseroperatelog, int>
    {

    }
}
