//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     做不该文件的修改内容。更改此
//     如果重新生成代码，文件将会丢失。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Abp.Application.Services.Dto;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Application
{
    public partial class GetTfmonitorabnormalPageInput : DefaultPagedResultRequest
    {
        
        /// <summary>
        /// 
        /// </summary>    
        public int? Id { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Exception { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string AbnormalContext { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string AddressName { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime? StartTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime? EndTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string MaxAlarmValue { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime? MaxAlarmTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Reason { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Remarks { get; set; }
    }
}

