//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     请不要对该文件内容进行修改。如果重新生成代码，文件内容将被覆盖。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Core
{
    public partial class Bspermission : IEntity<int>,IHasCreationTime
    {
        public Bspermission()
        {
        }
        
        public bool IsTransient()
        {
            return EqualityComparer<int>.Default.Equals(this.Id, default(int));
        }

        /// <summary>
        /// 
        /// </summary>    
        public int Id { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int PrivilegeMaster { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string PrivilegeMasterValue { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int PrivilegeAccess { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string PrivilegeAccessValue { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public int PrivilegeOperation { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CreationTime { get; set; }

    }
}