//------------------------------------------------------------------------------
// <autogenerated>
//     此代码是由 CodeSmith 模板生成的。
//
//     请不要对该文件内容进行修改。如果重新生成代码，文件内容将被覆盖。
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

// ReSharper disable once CheckNamespace
namespace CodeSmith.Abp.Template.Test.Core
{
    public partial class Bsbutton : IEntity<int>,IAudited,ICreationAudited,IHasCreationTime,IModificationAudited
    {
        public Bsbutton()
        {
            ButtonBsmenubuttons = new List<Bsmenubutton>();
            ButtonBsuseroperatelogs = new List<Bsuseroperatelog>();
        }
        
        public bool IsTransient()
        {
            return EqualityComparer<int>.Default.Equals(this.Id, default(int));
        }

        /// <summary>
        /// 
        /// </summary>    
        public int Id { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string Text { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string RunEvent { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public string IconClass { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime CreationTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public long? CreatorUserId { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public System.DateTime? LastModificationTime { get; set; }
        /// <summary>
        /// 
        /// </summary>    
        public long? LastModifierUserId { get; set; }

        public virtual ICollection<Bsmenubutton> ButtonBsmenubuttons { get; set; }
        public virtual ICollection<Bsuseroperatelog> ButtonBsuseroperatelogs { get; set; }
    }
}